name: Vinted Tracker
on:
  schedule:
    - cron: "*/10 * * * *"  # Toutes les 10 minutes
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run Vinted Tracker
        run: python vinted-tracker.py
